name: AntiCombatLog
version: '${project.version}'
main: net.badbird5907.anticombatlog.AntiCombatLog
api-version: 1.17
depend:
  - Citizens
softdepend:
  - floodgate
commands:
  anticombatlog:
    description: main command
    aliases:
      - combat
      - combatlog
  resettag:
    description: reset combat tag
    aliases:
      - resetcombattag
    permission: anticombatlog.command.resettag
